### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by pierrepo** [data-fun/3d-scere#2]
- [x] Add instructions to setup environment
- [x] Mention required data (i.e filenames) (later linked to a Zenodo repo)
- [x] Add instructions to run the dashboard

**Comment by Thibault-Poinsignon** [comment]
Currently the instructions are for a local run of the dashboard.

**Comment by pierrepo** [comment]
Perfect! This is all we need.

**Comment by Thibault-Poinsignon** [comment]
Great, Can you run it?

**Comment by pierrepo** [comment]
Nope :cry:  See https://github.com/data-fun/3d-scere/issues/9
