### ISSUE TITLE
Position of slider in the 3D distances tab

### ISSUE THREAD

**Issue by pierrepo** [data-fun/3d-scere#23]
In the 3D distances tab, the slider is currently before the histogram plot. Since the slider has no effect on the histogram but only modifies the network representation, it would be more sensible to move the slider between the histogram and the network plot.

![image](https://user-images.githubusercontent.com/733861/132683705-4f242f58-d299-402a-a045-3f634bbafc0b.png)

**Comment by Thibault-Poinsignon** [comment]
> Since the slider has no effect on the histogram

It does, the black dashed line dynamically represent the threshold. It will be specified in the (?) next to "3D distance threshold".
Knowing that, I think it's clearer to keep the slider here.
