### ISSUE TITLE
Display gene chromosome number and strandness in hover info box

### ISSUE THREAD

**Issue by pierrepo** [data-fun/3d-scere#25]
Could you please add gene chromosome number and strandness in hover info box provided in the 2D representation of genome (tab 1)?

![image](https://user-images.githubusercontent.com/733861/132689408-893ea6ba-bb6a-4773-a2d1-87ad9fe2f693.png)

Could also replace `x` by `position` and remove `y` (that would be the chomosome number)

**Comment by Thibault-Poinsignon** [comment]
Yes, it is planned as a part of #7.
